a = input('Digita logo o número, rapais')
print('O tipo primitivo desse valor é', type(a))
print('Só tem números?', a.isnumeric())
print('Só tem letras?', a.isalpha())
print('É alfanumerico?', a.isalnum())
print('?', a.isascii())
print('?', a.isdecimal())
print('Tem espaços?', a.isspace())
print('Tem numeros e letras?', a.isalnum())
print('Totalmente em maiúscula?', a.isupper())
print('Tem letras minúsculas?', a.islower())
print('?', a.isdigit())
print('?', a.isidentifier())
print('É imprimível?', a.isprintable())
print('Está captalizada?', a.istitle())